#Fill here the Google Maps API keys for your application
#In this sample:
#For development and test, we have only one possible host (localhost:3000), so there is only a single key associated with the mode.
#In production, the app can be accessed through 2 different hosts: thepochisuperstarmegashow.com and exmaple.com. There then needs a 2-key hash. If you deployed to one host, only the API key would be needed (as in development and test).

development:
 ABQIAAAATwnOuLl3-g4NXRBY8ZeMeRQRV-Q8hqrwoXHJ6kKMHbc9vA0cLBRVecvmbowB603ksp6Q-vLmaml8kw

test:
 ABQIAAAATwnOuLl3-g4NXRBY8ZeMeRQRV-Q8hqrwoXHJ6kKMHbc9vA0cLBRVecvmbowB603ksp6Q-vLmaml8kw

production:
 example.com: ABQIAAAATwnOuLl3-g4NXRBY8ZeMeRQRV-Q8hqrwoXHJ6kKMHbc9vA0cLBRVecvmbowB603ksp6Q-vLmaml8kw
